### ISSUE TITLE
[FEAT] 추천 비추천 값 가져오기

### ISSUE THREAD

**Issue by inrir** [CSID-DGU/2022-1-OSSP2-3K1S-3#12]
## 📝  To-do

- [x] 경로, 추천, 비추천 테이블 생성
- [x] dotenv 라이브러리 생성
- [x] 추천, 비추천 req 받고 데이터베이스 갱신받기

**Comment by inrir** [comment]
Merge 완료
