### ISSUE TITLE
[ADD] 반경 데이터를 받아서 합산된 추천 수와 추천 상세보기 API 구현

### ISSUE THREAD

**Issue by inrir** [CSID-DGU/2022-1-OSSP2-3K1S-3#29]
## 📌  Feature Issue

반경 데이터에 대한 id 값이 복수 값이므로 복수의 추천 테이블의 컬럼 값을 합산해서 응답해줍니다.

## 📝  To-do

- [ ] 반경 데이터로 id 값을 추출해준다.
- [ ] 추출된 데이터 값으로 추천 수를 합산해주고 응답한다.
- [ ] 추출된 데이터 값으로 추천 상세를 합산해서 상위 2항목과 기타 2항목을 응답해준다.
